[package]
name = "click_the_square"
version = "0.2.1"
authors = ["HopesHigh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14"
rand = "0.7"
